p5/Controllers/ReparationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using p5.Data;
using p5.Models;

namespace p5.Controllers
{
    public class ReparationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReparationsController(ApplicationDbContext context)
        {
            _context = context;
        }
        //ici
        //public IActionResult Index(int voitureId)
        //{
        //    var reparations = _context.Reparation.Where(c => c.VoitureId == voitureId).ToList();
        //    return View(reparations);
        //}

        // GET: Reparations
        public async Task<IActionResult> Index()//Index(int voitureId)
        {
            return _context.Reparation != null ?
                        View(await _context.Reparation.Include(r => r.Voiture).ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Reparation'  is null.");
        }

            // GET: Reparations/Details/5
            public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Reparation == null)
            {
                return NotFound();
            }

            var reparation = await _context.Reparation
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reparation == null)
            {
                return NotFound();
            }

            return View(reparation);
        }

        // GET: Reparations/Create
        public async Task<IActionResult> Create()
        {
            var voitureList = await _context.Voiture.ToListAsync();
            //ici creation de la liste "categorie"
            var categories = new List<string>
    {

          "---",
          "Climatisation",
        "Moteur",
        "Carrosserie",
        "Système de freinage",
        "Système d'allumage", 
        "Pneumatique",
    };
            ViewBag.Voitures = new SelectList(voitureList, "Id", "Marque");
            ViewBag.Categories = new SelectList(categories);

            

            return View();
            }

            // POST: Reparations/Create
            // To protect from overposting attacks, enable the specific properties you want to bind to.
            // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create(CreateReparationModel createReparationModel)
            {

                _context.Reparation.Add(new Reparation
                {
                    Categorie = createReparationModel.Reparation.Categorie,
                    VoitureId = createReparationModel.Voiture.Id
                });
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // GET: Reparations/Edit/5
            public async Task<IActionResult> Edit(int? id)
            {
                if (id == null || _context.Reparation == null)
                {
                    return NotFound();
                }

                var reparation = await _context.Reparation.FindAsync(id);
                if (reparation == null)
                {
                    return NotFound();
                }
                return View(reparation);
            }

            // POST: Reparations/Edit/5
            // To protect from overposting attacks, enable the specific properties you want to bind to.
            // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, [Bind("Id,Categorie")] Reparation reparation)
            {
                if (id != reparation.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(reparation);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ReparationExists(reparation.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(reparation);
            }

            // GET: Reparations/Delete/5
            public async Task<IActionResult> Delete(int? id)
            {
                if (id == null || _context.Reparation == null)
                {
                    return NotFound();
                }

                var reparation = await _context.Reparation
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (reparation == null)
                {
                    return NotFound();
                }

                return View(reparation);
            }

            // POST: Reparations/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                if (_context.Reparation == null)
                {
                    return Problem("Entity set 'ApplicationDbContext.Reparation'  is null.");
                }
                var reparation = await _context.Reparation.FindAsync(id);
                if (reparation != null)
                {
                    _context.Reparation.Remove(reparation);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            private bool ReparationExists(int id)
            {
                return (_context.Reparation?.Any(e => e.Id == id)).GetValueOrDefault();
            }
        }
    } 

p5/Controllers/VoituresController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using p5.Data;
using p5.Models;


namespace p5.Controllers
{
    public class VoituresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VoituresController(ApplicationDbContext context)
        {
            _context = context;
        }
       

        // GET: Voitures
        public async Task<IActionResult> Index()
        {
            return _context.Voiture != null ?
           
            View(await _context.Voiture.Include(v => v.Reparations)
                        .ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Voiture'  is null.");
            return View(Index);
        }

        // GET: Voitures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Voiture == null)
            {
                return NotFound();
            }

            var voiture = await _context.Voiture
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            return View(voiture);
        }

       

        // GET: Voitures/Create
        public IActionResult Create()
        {
            var marques = new List<string>()
            {
                "MARQUE",
        "PEUGEOT",
        "CITROEN",
        "RENAULT",
        "vw",
        "BMW",
        "MERCEDES",
        "FORD",
        "CHRYSLER",
        "TOYOTA"
            };
            ViewBag.Marques = new SelectList(marques);
            return View();
        }

        // POST: Voitures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Marque,Modele")] Voiture voiture)
        {
            if (ModelState.IsValid)
            {
                _context.Add(voiture);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(voiture);
        }

        // GET: Voitures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Voiture == null)
            {
                return NotFound();
            }

            var voiture = await _context.Voiture.FindAsync(id);
            if (voiture == null)
            {
                return NotFound();
            }
            return View(voiture);
        }

        // POST: Voitures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Marque,Modele")] Voiture voiture)
        {
            if (id != voiture.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(voiture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VoitureExists(voiture.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(voiture);
        }

        // GET: Voitures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Voiture == null)
            {
                return NotFound();
            }

            var voiture = await _context.Voiture
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                return NotFound();
            }

            return View(voiture);
        }

        // POST: Voitures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Voiture == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Voiture'  is null.");
            }
            var voiture = await _context.Voiture.FindAsync(id);
            if (voiture != null)
            {
                _context.Voiture.Remove(voiture);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VoitureExists(int id)
        {
            return (_context.Voiture?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

p5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - p5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/p5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">p5</a>
                <a>
                    <img src="https://axa365-my.sharepoint.com/:i:/r/personal/a114sr_login_axa/Documents/Images/imagecompteur%20logov1.png?csf=1&web=1&e=iFoWNe">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Voitures" asp-action="Index">Voiture</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reparations" asp-action="Index">Reparation</a>
                        </li>
                     </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - p5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>